let guestList2 = ["Mubashir", "Anas", "Rehan"];
console.log(`I would like to invite you to dinner ${guestList2[0]}`);
console.log(`I would like to invite you to dinner ${guestList2[1]}`);
console.log(`I would like to invite you to dinner ${guestList2[2]}`);
console.log("I just heared that Rehan can't make the dinner");
guestList2.pop();
guestList2.push("Amir");
console.log(`I would like to invite you to dinner ${guestList2[0]}`);
console.log(`I would like to invite you to dinner ${guestList2[1]}`);
console.log(`I would like to invite you to dinner ${guestList2[2]}`);
console.log("Hey guys, I found a bigger dinner table");
guestList2.unshift("Jawad");
guestList2.splice(2, 0, "Hassan");
guestList2.push("Junaid");
console.log(`I would like to invite you to dinner ${guestList2[0]}`);
console.log(`I would like to invite you to dinner ${guestList2[1]}`);
console.log(`I would like to invite you to dinner ${guestList2[2]}`);
console.log(`I would like to invite you to dinner ${guestList2[3]}`);
console.log(`I would like to invite you to dinner ${guestList2[4]}`);
console.log(`I would like to invite you to dinner ${guestList2[5]}`);